apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/cilium
  - ../../../base/cert-manager
  - ../../../base/csi-driver-smb
  - ../../../base/intel-device-plugins
  - ../../../base/kubelet-csr-approver
  - ../../../base/metrics-server
  - ../../../base/node-feature-discovery
  - ../../../base/tailscale
  - headlamp
  - tailscale
