apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium.yaml
  - csi-driver-smb.yaml
  - headlamp.yaml
  - intel.yaml
  - jetstack.yaml
  - kubelet-csr-approver.yaml
  - metrics-server.yaml
  - node-feature-discovery.yaml
  - prometheus-community.yaml
  - rook.yaml
  - tailscale.yaml
