apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/cert-manager
  - ../../base/headlamp
  - ../../base/tailscale
  - headlamp-ingress.yaml
  - tailscale-secret.sops.yaml
  - tailscale-helmrelease.yaml
