apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/kube-prometheus-stack
  - ../../../base/flux-webhook
  - kube-prometheus-stack
  - flux-webhook
patches:
  - path: kube-prometheus-stack/helmrelease-patch.yaml
