apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/jellyfin
  - cifs-secret.sops.yaml
  - cifs-pv.yaml
  - ingress.yaml
patches:
  - target:
      kind: PersistentVolumeClaim
      name: jellyfin-config
    patch: |-
      - op: add
        path: /spec/storageClassName
        value: ceph-block
