---
apiVersion: v1
kind: Service
metadata:
  name: ceph-dashboard-tailscale
  namespace: rook-ceph
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: ceph-m720q
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app: rook-ceph-mgr
    rook_cluster: rook-ceph
  ports:
    - port: 443
      targetPort: 7000
      protocol: TCP
