apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/cilium
  - ../../base/cert-manager
  - ../../base/kubelet-csr-approver
  - ../../base/kube-prometheus-stack
  - ../../base/rook-ceph-operator
  - ../../base/tailscale
  - ../../base/flux-webhook
  - api-proxy
  - flux-webhook
  - kube-prometheus-stack
  - rook-ceph-cluster
  - tailscale
patches:
  - path: kube-prometheus-stack/helmrelease-patch.yaml
