apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/cilium
  - ../../base/cert-manager
  - ../../base/tailscale
  - tailscale-secret.sops.yaml
  - api-proxy.yaml
