---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/headlamp
  - kubeconfig-secret.yaml
  - api-proxy-egress.yaml
  - ingress.yaml
patches:
  - path: helmrelease-patch.yaml
