apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources.yaml
  - infrastructure-core.yaml
  - infrastructure.yaml
  - rook-ceph-operator.yaml
  - rook-ceph-cluster.yaml
