---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph-cluster
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/core/overlays/m720q/rook-ceph-cluster
  prune: true
  wait: true
  timeout: 10m0s
  dependsOn:
    - name: rook-ceph-operator
  healthCheckExprs:
    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      current: >-
        status.phase == 'Ready' &&
        (status.ceph.health == 'HEALTH_OK' || status.ceph.health == 'HEALTH_WARN')
      failed: >-
        status.conditions.exists(e, e.type == 'Ready' && e.status == 'False')
