apiVersion: ENC[AES256_GCM,data:xdQ=,iv:jYq2ujhnYaVjaXNz97NFaupkh6Z6WAMnZlIwP+byq04=,tag:TvNFaOftpVswmIWYz7wkbw==,type:str]
kind: ENC[AES256_GCM,data:xx+CY0G9,iv:9Kap7FF7PbnbMweUNnRcm7YuJfMIpczbtZ9RD9+JZso=,tag:rPB8hMsNANZtkMI+Teuhmw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:pLxWwp7fP/q6vm6NQ7s6V+t3uqUsTMQLQC7v,iv:iZsXOV35L7mG2cGIV+t7W6I7lXobmRZJk4iEv7AFBdE=,tag:tOrKHPwTLi9DT9sMDBb3+A==,type:str]
    namespace: ENC[AES256_GCM,data:rTdUT7w4xJuIvA==,iv:asX22xdGp9YZjZIC6ZvnLsYfFB9fMHP1HEyj5XQBvQU=,tag:iaAGbnsbjLTlHl9goUrmMQ==,type:str]
stringData:
    client_id: ENC[AES256_GCM,data:2kyHMXLe4QaBf6nu5L6vD2gGt5fgK0sgtk19dOBNODk=,iv:GQBDwu9XIJIxQKKEep5PZ8rax1KuYcKG3nZ7gFLffhU=,tag:co+XIfIYA8xRPV7YyRB5+Q==,type:str]
    client_secret: ENC[AES256_GCM,data:v7SQlAA2uIbqiRfpJLvU864U/CoFbWUgcXyjhq+ez6TkNf81lBc98+8L0FRZUPyuGExWUaNy+ZoTXC/Hb27bcw==,iv:Cn4NuNNLpjPF7JIEoz2YH4EmedNxBJMu2JYuXVIqKpA=,tag:gDA9KB99ipaQEgSmU3lvug==,type:str]
sops:
    age:
        - recipient: age1helw9qcwl8lfy8xwm5cecnn2ljxlafhlplg3dehpk7ma4l94695qmqm9zg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTUHd4b0N5Mk1CeDlHTkFp
            T2ZIZnBpdjdaSGdSRTErdlRHZklhTWpRRFhZCmFJeE1lY3AxZWd3TTJrL0kvTmpH
            Um9ORkgvTUV0M21wODdUQitQY21wbDgKLS0tIEY1UTFBQnpnbUY3OUl4TnQvOE5i
            U2hnR1lqRTQ2QXNTbHhSQk93TGh5Mk0KyIaNBlog9e679aUMaarM6BzyCfCyZOjG
            mgCe95ToIIzVGPx/tKMTCdj56H3ejYx4ffIOVUPpeeJwiu+I1oSctw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-28T02:32:43Z"
    mac: ENC[AES256_GCM,data:SWLWseCEyxHdmm7Sn6Z+7C0wPyvJKhzlD+QGnuVLLqB7I85bR9rjaZGa06IvLXd4xnlrzpIIeGRYR8uPzWjNb+7dKfs8QR4C8jk+rTOiQ1C0IIrpQemt0EEiB7KK23tbplqh78vHIGXQCmM/IL/sOI1dTslmkPn5Ck26YSfeYbs=,iv:CLVr8Ek2XEf8ablW6QpOAZQHRk1XfVJemgDNkBTLyO8=,tag:Xtr57CM5kcDNjIToPc1b1g==,type:str]
    pgp:
        - created_at: "2025-11-28T02:32:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxQ26yvYdZ3KARAAi4wpzg41rb8F2z3sklKUugnOAjnAZmGueqoVB1QF4LZ/
            xPLdZryhoj1fHo4tIHE8btjtdFm2sjjvcAxCZhd8yBfgNidXeVSPgycelwUTUACm
            hA/LpJMuDAHVaTePNLMip1QVGw2EXXQd7DMdG7WjJLkgWmCNnGuk3Nm4ubszEPaB
            FQA0XUFJmh/+Lge7qZK+Jv9Nriloqbv3EqgYQxgt+pp0IcTyhnvIWLYZR+rMS2P5
            knJP9dEWvDY+kjCKTxyn0DzsbW9e8ejYKzZlGFHJyqX7ZLFZRWhc+gFZSFSQ604N
            r+CuVC7YfF4sSX3AjZK/h3rK+w28nV6rqFPtEH55s+skbTfTi0QcFwG+hASXYDFA
            ItCndjYpUFSz54NUCgwAkGhm13S274PgYIWyRDN2ItB08qbknw8tNA0GuwDGoWRn
            IPR/8VfHiuz2TLM/G5Chle3F6eXW65Qut3PZde83BoD14IBUWb62JsYpl4GB2C/z
            pAluIbsFnjfwOpKPtF1YGYgYP97KdHvVVmT2z6EAlfb33rowTcCcP91ILTW37IRz
            UU6eRW04JgIb8maxTv2167P8OUDqgr8G8o3ALItGfGDLnxMw6io+/bKEZUBn+oeb
            Z9bAEp9Swd5DYF0ZapFWih/YbT6cs+2Mabb03M+yeilnTHGnrdKNhPE4eKMbhWnS
            XAH7PDYio1Fnzxxlh2g2yCoVAFrAAVEkaPgOXvHjNKOCp1KncKEKFSGlzJL12j6H
            p0cMdijcozGjTGVjoSdj9LoH3j5WRU2WzSiDQxLFX9YhFSWYS/hzh6Mdfwj7
            =zIf3
            -----END PGP MESSAGE-----
          fp: 6636CBF9CE1DE1A8
    unencrypted_suffix: _unencrypted
    version: 3.11.0
