apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-prometheus-stack-secret.sops.yaml
  - grafana-ingress.yaml
  - grafana-dashboard-node-exporter-full.yaml
  - grafana-dashboard-ceph-cluster.yaml
